### ISSUE TITLE
nodejs connect mysql db fail exception throw

### ISSUE THREAD

**Issue by slee124565** [slee124565/flh-envmonitor#2]
[2016-11-01 04:35:34] Demo get Sensor Value!

/var/FLH-Web/nodejs/server.js:394
                        throw err;
                              ^
Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (/var/FLH-Web/nodejs/node_modules/mysql/lib/Connection.js:373:13)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:92:17)
    at Socket._onTimeout (net.js:326:8)
    at Timer.unrefTimeout [as ontimeout] (timers.js:418:13)
    --------------------
    at Protocol._enqueue (/var/FLH-Web/nodejs/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/var/FLH-Web/nodejs/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/var/FLH-Web/nodejs/node_modules/mysql/lib/Connection.js:123:18)
    at port (/var/FLH-Web/nodejs/server.js:387:13)
    at Layer.handle [as handle_request] (/var/FLH-Web/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/FLH-Web/nodejs/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/FLH-Web/nodejs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/FLH-Web/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at /var/FLH-Web/nodejs/node_modules/express/lib/router/index.js:277:22
    at param (/var/FLH-Web/nodejs/node_modules/express/lib/router/index.js:349:14)

**Comment by slee124565** [comment]
nodejs service should wait for mysql service start
